# версия Docker Compose
version: '3.8'

services:
  aop-app:
    build: .
    image: t1-aop-app
    container_name: t1-aop-app-container
    ports:
      - "8080:8080"
    depends_on:
      - aop-db
#    переменные окружения
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://aop-db:5432/t1-postgres
#      - DB_NAME=t1-postgres
#      - POSTGRES_USER=root
#      - POSTGRES_PASSWORD=root
#      - DB_HOST=db
#      - DB_PORT=5432
  # описание контейнера db
  aop-db:
    # образ, из которого должен быть запущен контейнер
    image: postgres:15-alpine
    container_name: aop-db-container
    # переменные окружения
    # volume и связанная с ним директория в контейнере
    ports:
      - "6542:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=t1-postgres
      - POSTGRES_USER=t1-user
      - POSTGRES_PASSWORD=sa