application-version: 1.0
logging:
    level:
        org:
            springframework: info
            springframework.orm.jpa: INFO
            springframework.orm.jpa.JpaTransactionManager: DEBUG
            springframework.transaction.interceptor: TRACE
        root: info
spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/t1-postgres
        driverClassName: org.postgresql.Driver
        username: t1-user
        password: sa
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                format_sql: true
        show-sql: true
    sql:
        init:
            mode: always
