application-version: 1.0
logging:
    level:
        org:
            springframework: info
            springframework.orm.jpa: INFO
            springframework.orm.jpa.JpaTransactionManager: DEBUG
            springframework.transaction.interceptor: TRACE
        root: info
spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/t1-postgres
        driverClassName: org.postgresql.Driver
        username: t1-user
        password: sa
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                format_sql: true
        show-sql: true
    sql:
        init:
            mode: always
    mail:
        host: smtp.yandex.ru
        username: antonovsacha@yandex.ru #todo: добавить свои данные
        password: "password" #todo: добавить  свои данные
        port: '465'
        ssl:
            enabled: true
    messages:
        encoding: utf-8
    main:
        allow-circular-references: true
t1:
    kafka:
        topic:
            name: "taskStatus"
            partition-count: 1
            enable: false
        consumer:
            props:
                servers: "localhost:9092"
                groupId: "taskConsumerGroup"
                maxPollRecords: 3
                enableAutoCommit: false
                sessionTimeoutMs: 10000
        producer:
            props:
                enable: true
                servers: "localhost:9092"
                sessionTimeoutMs: 10000
                enableIdempotence: false
