create table if not exists tuser (
  id bigint generated by default as identity primary key,
  username text unique,
  password text
);

create table if not exists ttask (
  id bigint generated by default as identity primary key,
  description text,
  status text,
  title varchar(300),
  user_id bigint references tuser on delete cascade,
  unique(description, title, user_id)
);
